#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | 选点页面: https://wloc-jack182617.yuanjie182617.workers.dev/
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Jack182617/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/Jack182617/wloc/ffde056/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/Jack182617/wloc/ffde056/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
